/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crosswordpuzzle;

import java.awt.Color;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout.ParallelGroup;
import javax.swing.JTextField;

/**
 *
 * @author Yavuz Algun
 */
public class OpeningDialog extends javax.swing.JDialog {
    
    public ArrayList<ArrayList<JTextField>> liste;
    public int N = 6;
    /**
     * Creates new form OpeningDialog
     */
    public OpeningDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        gridLayout(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        satirSayisiTextField = new javax.swing.JTextField();
        olusturButton = new javax.swing.JButton();
        cozButton = new javax.swing.JButton();
        randomButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout TablePanelLayout = new javax.swing.GroupLayout(TablePanel);
        TablePanel.setLayout(TablePanelLayout);
        TablePanelLayout.setHorizontalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        TablePanelLayout.setVerticalGroup(
            TablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        jLabel1.setText("Satır/Sutun Sayisi: ");

        olusturButton.setText("OLUSTUR");
        olusturButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olusturButtonActionPerformed(evt);
            }
        });

        cozButton.setText("COZ");
        cozButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cozButtonActionPerformed(evt);
            }
        });

        randomButton.setText("RANDOM");
        randomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(satirSayisiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(olusturButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(randomButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cozButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(satirSayisiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(olusturButton)
                    .addComponent(cozButton)
                    .addComponent(randomButton))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void olusturButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olusturButtonActionPerformed
        N = Integer.parseInt(satirSayisiTextField.getText());
        gridLayout(); 
    }//GEN-LAST:event_olusturButtonActionPerformed

    private void cozButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cozButtonActionPerformed
        String[][] newTable = new String[N][N];
        Search.N = N;
        try {
            newTable = Search.kurVeCoz(getArray(liste));
            for(int i=0;i<N;i++){
                for(int j=0;j<N;j++){
                    if(newTable[i][j].equals("/")){
                        liste.get(i).get(j).setBackground(Color.BLACK);
                    } else {    
                        liste.get(i).get(j).setText(newTable[i][j]);
                    }
                }
            }
        } catch (IOException ex) {
            olusturButtonActionPerformed(evt);
            cozButtonActionPerformed(evt);
        }
    }//GEN-LAST:event_cozButtonActionPerformed

    private void randomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomButtonActionPerformed
        for(int i = 0;i<(N);i++){
            int randX = (int) (Math.random()*N);
            int randY = (int) (Math.random()*N);
            liste.get(randX).get(randY).setBackground(Color.BLACK);
            liste.get(randX).get(randY).setText("/");
        }
    }//GEN-LAST:event_randomButtonActionPerformed

    public void gridLayout(){
        TablePanel.removeAll();
        TablePanel.setLayout(new GridLayout(N, N, 0, 0));
        liste = new ArrayList<>();
        for(int i = 0;i<N;i++){
            ArrayList<JTextField> altListe = new ArrayList<>();
            for(int j = 0;j<N;j++){
                altListe.add(new JTextField());
                TablePanel.add(altListe.get(j));
            }
            liste.add(altListe);
        }
        pack();
    }
    
    public String[][] getArray(ArrayList<ArrayList<JTextField>> liste){
        String[][] TableArray = new String[liste.size()][liste.size()];
        for(int i=0;i<liste.size();i++){
            for(int j=0;j<liste.size();j++){
                 String temp= liste.get(i).get(j).getText().trim();
                 if(temp.length() == 0){
                     temp = "-";
                 }
                 TableArray[i][j] = temp;
            }
        }
        return TableArray;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpeningDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpeningDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpeningDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpeningDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OpeningDialog dialog = new OpeningDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TablePanel;
    private javax.swing.JButton cozButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton olusturButton;
    private javax.swing.JButton randomButton;
    private javax.swing.JTextField satirSayisiTextField;
    // End of variables declaration//GEN-END:variables
}
